name: 'Chromatic Deployment'

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Node.js 버전을 20.x로 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      # Yarn 설치 및 패키지 설치
      - run: yarn
      # Chromatic 배포
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
